### PR TITLE
Add setter for Container Customizer on AbstractMessageChannelBinder

### PR DESCRIPTION
**Pull request by mattdupuy**
Based on suggestion in #2345, add a setter for Container Customizer and update documentation accordingly

### CODE REVIEW

**Comment by sobychacko** [comment]
@mattdupuy Did you verify that these changes worked for your scenario? I wonder whether we need a test to verify.

**Comment by mattdupuy** [comment]
@sobychacko It works with the use of reflection in the current version of the framework, as mentioned in issue #2345, so adding the setter will allow me to remove the reflection and have the expected behavior.
If you have an idea of a test to add, let me know.

**Comment by sobychacko** [comment]
Ok, sounds good. Since it is only a setter change, I think we can merge it without the test.

**Comment by sobychacko** [comment]
Merged upstream. Thanks for the PR!

**Pull request closed without merging**
