### PR TITLE
GH-1294 fixed NPE with wildcarded MimeTypes

### PR DESCRIPTION
**Pull request by jmax01**
[Do not merge] has caching for schemas discovered via reflection of the targetClass.
Questions are marked TODO 1294

Resolves spring-cloud/spring-cloud-stream#1294

### CODE REVIEW

**Comment by olegz** [comment]
@jmax01 added few comments. The bottom line is that given that we're very close to a RELEASE, I am reluctant to address any enhancements right now, so just bugs. We can always add things in the future. Also as I've mentioned one can always provide a custom converter if the behavior of the provided one is not sufficient.

**Comment by sabbyanandan** [comment]
Hi, @jmax01. Any thoughts on @olegz's comment?

**Comment by jmax01** [comment]
Sorry have been really busy, I will try to take a peek tomorrow.

**Comment by olegz** [comment]
Thanks @jmax01 
Let us know. Given that GA is scheduled for March 29th we'd like your two current PRs to make it. So if you need some help let us know as well

**Comment by jmax01** [comment]
Once I get my DLQ with raw headers support working I will be able to take a look.

**Comment by olegz** [comment]
@jmax01 I am closing this one in favor of https://github.com/spring-cloud/spring-cloud-stream/pull/1340
See the commit comment.
Basically the NPE is addressed following the defensive programming practices. Also we do support cases where both resolution methods return null using the `ReflectDatumReader` over the provided type.
As commit comment states, we recognize that it may still not be enough, but given that this is a `MessageConverter` user can always provide a custom one, yet over time we can evolve this one.

**Pull request closed without merging**
