### PR TITLE
Move spring-cloud-stream tuple

### LINKED ISSUE #326: Migrate `spring-cloud-stream-tuple` out

### PR DESCRIPTION
**Pull request by ilayaperumalg**
- The `spring-cloud-stream-tuple` is now split into `spring-tuple`, `spring-integration-tuple` along with `spring-batch-tuple`
  - Update dependencies to use the new ones

This resolves #326

### CODE REVIEW

**Comment by ilayaperumalg** [comment]
Before merging this PR, the following repos need to be moved into `spring-projects` org:

1) https://github.com/ilayaperumalg/spring-tuple
2) https://github.com/ilayaperumalg/spring-integration-tuple
3) https://github.com/ilayaperumalg/spring-batch-tuple

The SCSt currently has `spring-tuple` and `spring-integration-tuple` as dependencies.

**Comment by markpollack** [comment]
Cool.  We should move this into a single repo under spring-project as a multi project mvn build, not 3 sep repos.

**Comment by artembilan** [comment]
??? Looks like we should have only one top-level `spring-tuple` project and all others can be simply moved to the particular projects like Spring Integration or Spring Batch.

The `integration` package and SI dependency should be removed from the `spring-tuple`, I guess.

**Comment by mbogoevici** [comment]
Merged w/https://github.com/spring-cloud/spring-cloud-stream/commit/69e484163cd578b45f7c1f738cce425a2ddf6cd4

**Pull request closed without merging**
