### PR TITLE
add missing accessors for configuration properties' array members

### PR DESCRIPTION
**Pull request by mbenson**
can't configure properly otherwise

### CODE REVIEW

**Comment by mbogoevici** [comment]
Hi @mbenson,

Thanks for the contribution.

Do you have a CLA signed? https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#sign-the-individual-contributor-license-agreement-icla

**Comment by mbogoevici** [comment]
Trying to reproduce this: passing the values as a comma separated list will work, but not the explicit array mapping. 

`spring.cloud.stream.kafka.binder.brokers=localhost:29092,localhost:19092` will work

`spring.cloud.stream.kafka.binder.brokers[0]=localhost:29092`
`spring.cloud.stream.kafka.binder.brokers[1]=localhost:19092` will not (and presumably the YML equivalent)

**Comment by mbenson** [comment]
I have signed the CLA, and have several PRs accepted into spring-boot and spring-cloud already.

**Comment by mbogoevici** [comment]
Cool, thanks. Just wanted to confirm. LGTM, merging.

**Pull request merged**
