### PR TITLE
Incorrect Confluent Schema Registry URL & Automatic Registration

### PR DESCRIPTION
**Pull request by wtfc63**
We encountered two problems while trying to get Spring Cloud Stream Schema running with the Confluent Platform:

1. When trying to fetch Schemas from the registry by extracting the Schema reference from the MIME type, the _ConfluentSchemaRegistryClient_ tries to get the Schema by its Id (which is unknown) instead of getting it by its _subject_ and _version_
1. Schemas that can be extracted from the payload are only registered automatically if the Schema reference can not be extracted from the MIME type. They should also be registered automatically if they can not be found in the registry, but can be extracted from the payload.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@wtfc63 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-stream&pullRequestId=845)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-stream&pullRequestId=845) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@wtfc63 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-stream&pullRequestId=845)!

**Comment by mbogoevici** [comment]
Thanks a lot for the contribution @wtfc63 - a note (for the future, hopefully!) - we would prefer PRs made from a topical branch as opposed to master. 

For this one - would it be possible to rebase this on top of the existing master? The interspersed/merged changes make the review a bit hard to process. Thanks!

**Comment by wtfc63** [comment]
Thanks, @mbogoevici for looking at the PR. Sorry for the branch thing, I'll keep that in mind for the next time.

The recent changes seem to have addressed my second point already. Therefore, I removed those changes again. Hopefully, the remaining changes should be pretty straight-forward.

**Pull request closed without merging**
