### PR TITLE
Use the SI EvaluationContext by default for Expression properties

### PR DESCRIPTION
**Pull request by ericbottard**

### CODE REVIEW

**Comment by markfisher** [comment]
I believe rather than using the `BeanFactory` for lookup, the "integrationEvaluationContext" should be injectable via `@Autowired`. cc @artembilan @garyrussell

**Comment by ericbottard** [comment]
It's always a decision between the lookup approach (urghh) and relying on a name (which could change)

But I'm definitely eager to know what we consider to be the best approach

**Comment by markfisher** [comment]
I don't think that bean name will change, but perhaps a compromise is to use `IntegrationContextUtils.INTEGRATION_EVALUATION_CONTEXT_BEAN_NAME` within the `@Qualifier`. That cannot change for backwards compatibility reasons.

**Comment by ericbottard** [comment]
Changed, added test

**Comment by markfisher** [comment]
LGTM; merging

**Comment by markfisher** [comment]
merged as https://github.com/spring-cloud/spring-cloud-stream/commit/80b1d28be1c8b9a23099b145fe2dcf472bfa9697 (added a newline at the end of the test class)

**Pull request closed without merging**
