### PR TITLE
[GH-1511] RetryTemplate per binding

### PR DESCRIPTION
**Pull request by nhomble**
Allow end users to optionally specify a retry template bean by name in their consumer properties so that different bindings can point to different retry templates.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@nhomble Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-stream&pullRequestId=1588)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-stream&pullRequestId=1588) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@nhomble Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-stream&pullRequestId=1588)!

**Comment by olegz** [comment]
Consider running full build before submitting a PR so you don't miss anything else `./mvnw clean install`

**Comment by nhomble** [comment]
@olegz it's no surprise the codecov went down :( any ideas how I can test a retry template is associated with a particular binding?

**Comment by olegz** [comment]
Let me review the PR first and we'll see what we should do

**Comment by olegz** [comment]
Merged with polishing https://github.com/olegz/spring-cloud-stream/commit/f01cb29b44b6992326482c43c28c9bf0225daada

**Comment by xyloman** [comment]
@olegz just ran across this issue and as we have been upgrading to the latest version of spring cloud we ran into this same issue.  I am a bit confused by PR and issue history associated with this and couldn't tell if this was merged into spring-cloud-stream or if this was just closed?

**Comment by xyloman** [comment]
Okay went through the github history and it looks like it was merged here: https://github.com/spring-cloud/spring-cloud-stream/commit/e9d22cb352f21984313daaf175476e35ad945488

**Pull request closed without merging**
