### PR TITLE
Issue #137: Some docs enhancements

### PR DESCRIPTION
**Pull request by kbastani**
Fixed docs syntax error with ModuleApplicationTests

### CODE REVIEW

**Comment by kbastani** [comment]
There was a syntax error in the docs in the example code for the TimerSource unit test class

**Comment by kbastani** [comment]
Added an emit log in the Source sample so you can see what the payload is that is being emitted on the interval.

**Comment by markfisher** [comment]
I don't think the logging on the source side is a good idea actually. What we really want for an initial "time | log" experience is to see the messages on the log sink side. The source side messages can be confusing.

I will push the semicolon addition though. Thanks for catching that!

**Comment by markfisher** [comment]
added missing semicolon here: https://github.com/spring-cloud/spring-cloud-stream/commit/cc71d66445c2d794d8800ee77dffbf1d7d21a4e6

**Pull request closed without merging**
