### PR TITLE
GH-1301 Add conversion to Flux Message Payload.

### PR DESCRIPTION
**Pull request by jmax01**
NOTE: Not sure if Message.create is the right answer

Resolves spring-cloud/spring-cloud-stream#1301

### CODE REVIEW

**Comment by sobychacko** [comment]
Hi @jmax01 Thanks for the PR. Quick question. Did you verify why/how simple types are getting converted? It looks to me that if there are appropriate converters then `ScSt` does the conversion, but fails for complex scenarios as yours that involve Avro.

**Comment by sobychacko** [comment]
Hi @jmax01 Could you please write some tests for these code changes? You can follow the same pattern as in the other reactive tests.

**Comment by sobychacko** [comment]
Hi @jmax01 pinging again - any chance you can address the testing concern on the PR? create a test case where you reproduce the issue and then verify that the changes address that. We are so close to the GA release and trying to see if we can include this in the GA or push it post-release. Any feedback is appreciated!

**Comment by jmax01** [comment]
Sorry on vacation, likely won't be able to do anything for at least a week.

On Apr 4, 2018 9:34 AM, "Soby Chacko" <notifications@github.com> wrote:

Hi @jmax01 <https://github.com/jmax01> pinging again - any chance you can
address the testing concern on the PR? create a test case where you
reproduce the issue and then verify that the changes address that. We are
so close to the GA release and trying to see if we can include this in the
GA or push it post-release. Any feedback is appreciated!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/spring-cloud/spring-cloud-stream/pull/1302#issuecomment-378664049>,
or mute the thread

**Comment by sabbyanandan** [comment]
@jmax01: Just a friendly follow-up. It'd be great if you can add the missing test; we would want to get this merged for the next milestone (2.1 M1). Thanks for your time and effort!

**Comment by jmax01** [comment]
I will try this week.

**Comment by olegz** [comment]
Actually we may want to hold on with this one as it cross-cuts with Spring Cloud Function's already existing functionality. In other words we may end up repeating the same code.

**Pull request closed without merging**
