### PR TITLE
Adding Spring Cloud Stream Version To Message Headers For Easier Debugging Of Issues

### PR DESCRIPTION
**Pull request by omercelikceng**
Resolves https://github.com/spring-cloud/spring-cloud-stream/issues/2814

### CODE REVIEW

**Comment by eomercelik** [comment]
Hello @sobychacko. Why did you revert the relevant commit? What’s the issue?"

**Comment by omercelikceng** [comment]
Hello @sobychacko. Why did you revert the relevant commit? What’s the issue?

**Comment by sobychacko** [comment]
Hi @omercelikceng, On our CI environments, we were getting the following error.

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:3.1.0:run (readme) on project spring-cloud-stream: An Ant BuildException has occured: Could not find org.springframework.cloud.internal.asciidoctor.ReadmeMain. Make sure you have it in your classpath

[ERROR] around Ant part ...<java classname="org.springframework.cloud.internal.asciidoctor.ReadmeMain" failonerror="yes" classpathref="readme.class.path">... @ 7:132 in /opt/jenkins/data/workspace/spring-cloud-stream-Moorgate-main-openjdk17-ci/core/spring-cloud-stream/target/antrun/build-main.xml
```

Can you see why we got this error? Looks like you added that antrun plugin as part of this PR.

**Comment by omercelikceng** [comment]
Yes, @sobychacko. I'm injecting the version at build time using the Maven Antrun Plugin. Actually, I don’t encounter this error on my local machine. It also seemed that no error occurred when the PR was merged. Do I have access to your environment? What approach can I take to resolve this? When I merged the code, it built successfully on your Jenkins. I’d really like to solve the issue, but I need to reproduce the problem, or I’d need to run some tests in your environment. Could you assist me with this?

**Comment by omercelikceng** [comment]
> Hi @omercelikceng, On our CI environments, we were getting the following error.
> 
> ```
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:3.1.0:run (readme) on project spring-cloud-stream: An Ant BuildException has occured: Could not find org.springframework.cloud.internal.asciidoctor.ReadmeMain. Make sure you have it in your classpath
> 
> [ERROR] around Ant part ...<java classname="org.springframework.cloud.internal.asciidoctor.ReadmeMain" failonerror="yes" classpathref="readme.class.path">... @ 7:132 in /opt/jenkins/data/workspace/spring-cloud-stream-Moorgate-main-openjdk17-ci/core/spring-cloud-stream/target/antrun/build-main.xml
> ```
> 
> Can you see why we got this error? Looks like you added that antrun plugin as part of this PR.

Hello @sobychacko, I apologize for the issue you’ve encountered.

I’ve investigated the problem, and it occurs when we build with the "**docs**" profile.

In the "**docs**" profile, there are specific configurations defined for the **maven-antrun-plugin** in the **spring-cloud-build** project. The **Spring Cloud Stream** project declares the **spring-cloud-build** project as its **parent POM**.

Along with my development, I’ve added **custom configurations** for the **maven-antrun-plugin** in the Spring Cloud Stream POM(spring-cloud-stream core). This is exactly where the issue arises.

I haven’t been able to pinpoint the exact cause yet, but I will continue investigating and open a pull request once I have a solution.

**Comment by omercelikceng** [comment]
@sobychacko , I reviewed the issue and considered various solutions, but I need your guidance.

Currently, in the **spring-cloud-build** project, within the **docs profile,** there are configurations defined for **maven-antrun-plugin** in the dependencyManagement section. (https://github.com/spring-cloud/spring-cloud-build/blob/main/pom.xml)

In my case, I used **maven-antrun-plugin** within **spring-cloud-stream-core**. Since **spring-cloud-build** is the **parent** POM for **spring-cloud-stream,** the phases specified in the **docs** profile of **spring-cloud-build** were triggered, leading to errors. Normally, this plugin was not executed. However, because I defined this plugin in the **spring-cloud-stream-core** POM, it caused all the phases defined in the parent POM(spring-cloud-build) to execute, leading to errors.

Additionally, in the spring-cloud-stream project, the usage of maven-antrun-plugin within the **docs profile** has been disabled. (https://github.com/spring-cloud/spring-cloud-stream/blob/main/docs/pom.xml)

My proposed solution is to set these phases to **"none"** in spring-cloud-stream-core to prevent the phases defined in spring-cloud-build from running. If this approach is acceptable to you, I will proceed with a pull request.

My solution : 

```
<properties>
      <generate-readme.phase>none</generate-readme.phase>
      <generate-docs.phase>none</generate-docs.phase>
  </properties>
```

**Comment by omercelikceng** [comment]
@olegz , if you allow, I would like to open a pull request with my new solution. Could you assist me with this?

**Comment by sobychacko** [comment]
@omercelikceng Please go ahead and submit a PR.

**Pull request closed without merging**
