### PR TITLE
Native Kafka ProducerConfig (like: client.id) support has been added

### PR DESCRIPTION
**Pull request by urgelacko**
Now key-value pairs under spring.cloud.stream.kafka.bindings.< channelName >.producer.config key are set as native Kafka producer configuration.
This is useful because this way we can configure all Kafka specific producer configuration values through application properties.

### CODE REVIEW

**Comment by mbogoevici** [comment]
Hi @urgelacko,

Did you sign the contributor agreement (https://support.springsource.com/spring_committer_signup) ? Thank you.

**Comment by mbogoevici** [comment]
Planning to address this as part of 1.1.0.M1 as we will have more flexibility with the Spring Integration Kafka 2.0 support.

**Comment by urgelacko** [comment]
I have signed the agreement now. Sorry for missing it first time.

As I see the merge request is in conflict state now. Should I resolve the conflicts or if these kind of missing parts are in the next version it is useless and we should just wait for the official solution?

**Comment by mbogoevici** [comment]
Hi Laszlo - no problem! Thanks for the contribution! I would advise waiting for the next version, and I've created https://github.com/spring-cloud/spring-cloud-stream/issues/531 to track this.

**Comment by urgelacko** [comment]
Thanks a lot we are waiting for it :)

**Comment by mbogoevici** [comment]
You're welcome - I will close this then in favour of the issue.

**Pull request closed without merging**
