### PR TITLE
GH-2922: TimestampExtractor ignored

### PR DESCRIPTION
**Pull request by qxv1612**

### CODE REVIEW

**Comment by sobychacko** [comment]
@qxv1612 Can you add your name as an author to the class and update the copyright year?

**Comment by qxv1612** [comment]
@sobychacko done

**Comment by sobychacko** [comment]
@qxv1612, Thank you for spotting this issue and for the PR! It is now merged upstream via https://github.com/spring-cloud/spring-cloud-stream/commit/eab86f81a8b34569f8075c352b4bb9602150fbc5.

**Comment by qxv1612** [comment]
@sobychacko That was fast. Thanks!

**Pull request closed without merging**
