### PR TITLE
Fix typo in `RabbitBinderConfigurationProperties`

### PR DESCRIPTION
**Pull request by detached**
Substitute adminAdresses with adminAddresses.

### CODE REVIEW

**Comment by mbogoevici** [comment]
Thanks @detached - do you have a CLA on file?

As a note, we should leave the old property in (at least for 1.0.x) and mark it as deprecated - to be removed in the future, as current applications that use the incorrect form and upgrade will break.

**Comment by detached** [comment]
@mbogoevici - yes I have.
May I create a issue for keeping track?

**Comment by mbogoevici** [comment]
Sure - please create an issue - thanks!

**Comment by mbogoevici** [comment]
Rebased, merged w/https://github.com/spring-cloud/spring-cloud-stream/commit/c1f4ba66d3f2d51d257304ed86192a3590f30f01 and additional corrections in https://github.com/spring-cloud/spring-cloud-stream/commit/daf454410cedf73f059ecfc71bd012627a2e79df

Also cherry-picked for 1.0.x

**Pull request closed without merging**
