### PR TITLE
StreamBridge's dynamic destinations should be closed on shutdown.

### PR DESCRIPTION
**Pull request by kurthong**
- if not, we might lose some messages on shutdown especially in case of kafka async mode producing.

### CODE REVIEW

**Comment by kurthong** [comment]
@olegz, Would you mind to explain why this PR was just closed, not merged? 
Github badges is somewhat important to me:-)

**Comment by sobychacko** [comment]
@kurthong This PR is merged upstream in `main` and back-ported to `4.0.x`. Do you see this as not merged? Please explain.

**Comment by kurthong** [comment]
> @kurthong This PR is merged upstream in `main` and back-ported to `4.0.x`. Do you see this as not merged? Please explain.

@sobychacko 
So, it was not intentional. Considering the history of this pull request, it was closed with unmerged commits. Later, Olegz pushed a commit that referenced this pull request. 

Therefore, the pull request itself is image and not image.
However the commit itself is image.

And contributors would be proud of that their PRs are merged into one of their favorite projects:-)
image

I hope you understand.

**Comment by sobychacko** [comment]
I don't follow what the issue is. I see your commit from this PR in the main commit history. https://github.com/spring-cloud/spring-cloud-stream/commits/main

**Comment by kurthong** [comment]
@sobychacko
Yes, I'm aware that my commit has been merged into your repository. And I'm proud of that:-)
Maybe Olegz is using GitHub differently. Normally, 'Closed' means that the PR was not accepted.
image

If you still don't understand what I mean, please let it go. It's not that big deal.

**Pull request closed without merging**
