### PR TITLE
#1202 Inconsistent use of this.prefix in AvroSchemaRegistryClientMessageConverter.resolveSchemaForWriting

### PR DESCRIPTION
**Pull request by jmax01**
Replaced hard coding with `this.prefix`

### CODE REVIEW

**Comment by olegz** [comment]
Thank you @jmax01 i'll see how it plays along with the similar change that I mentioned earlier (#1198)

**Comment by olegz** [comment]
@jmax01 I merged it as I noticed a minor change in your PR that is not present in the one o was referring to, so I'll rebase that one.
Once again thank you for the contribution

**Comment by garyrussell** [comment]
@jmax01 In future, please limit commit headlines to 50 characters; it makes it easier to read one-line commit summaries.

We generally use the guidelines in [Pro Git](https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project).

**Comment by jmax01** [comment]
No problem.

**Pull request closed without merging**
