### PR TITLE
Fix the full names in shared.beans

### PR DESCRIPTION
**Pull request by SuperOranges**
Fix the full names of ConsumerConfigCustomizer and ProducerConfigCustomizer in shared.beans.

### CODE REVIEW

**Comment by omercelikceng** [comment]
Hello,

Which version are you using? In 2022, these classes were moved to a different path. (https://github.com/spring-cloud/spring-cloud-stream/commit/e522450f8ec91f64105f5d1f13b7c83818ee6bbe)
Therefore, the paths provided in the current main branch are correct.

You might be reviewing a different version.

**Comment by SuperOranges** [comment]
Hello,
   I'm glad to hear from you.
   i am using spring-cloud-stream-binder-kafka-core 3.2.10.
   ConsumerConfigCustomizer and ProducerConfigCustomizer  in this version confuses me.
   Thank you, now my doubts have been answered.

**Comment by SuperOranges** [comment]
Hello，
emm.....will 3.2.x be updated?

**Comment by omercelikceng** [comment]
I have opened an issue. Depending on the outcome of the discussion, we can proceed with the development. After a decision is reached, you can open a pull request if you like. If you don't have available time, I will make the related development.

**Comment by SuperOranges** [comment]
Thank you,i will be part of this discussion. I am glad to open a pull request if the decison is reached.

**Pull request closed without merging**
