### PR TITLE
Support @StreamListener in PollableChannels

### LINKED ISSUE #436: Support @StreamListener with PollableChannels

### PR DESCRIPTION
**Pull request by ilayaperumalg**
- If the StreamListener is annotated with PollableChannel, then bridge the pollable channel to subscribable channel
and use the subscribable channel to subscribe to the StreamListenerMessageHandler

This resolves #436

### CODE REVIEW

**Comment by ilayaperumalg** [comment]
Created this PR on top of the PR https://github.com/spring-cloud/spring-cloud-stream/pull/415 so that we can make use of the `PollableToSubscribableBridge`. The actual change for this PR is from this commit: https://github.com/spring-cloud/spring-cloud-stream/pull/460/commits/985d2f9a298c7d75206c5d7a849a779248f1f3b3

**Comment by garyrussell** [comment]
I need to look at this more closely, but it seems much more complicated than needed.

I think we simply need to wrap the `StreamListenerMessageHandler` in a `PollingConsumer` rather than creating a bridge.

But, I see the bridging mechanism is already in the `BindableProxyFactory`, using a `ConsumerEndpointFactoryBean` - I need to talk to @mbogoevici to understand why that was the approach.

**Comment by garyrussell** [comment]
That said, does this "feature" even make sense? With an unbounded pollable input channel, the binder is likely to outpace any app and memory will fill up. That can be avoided with a bounded channel but, even then, the binder will immediately ack queued messages and they will be lost in the event of a failure.

**Comment by ilayaperumalg** [comment]
> I think we simply need to wrap the StreamListenerMessageHandler in a PollingConsumer rather than creating a bridge

yeah, that's a good idea. I will give that a try.

For the feature question, I think we still want to support `PollableChannel` with the `@StreamListener` when someone has a usecase where the binder is likely to receive messages no faster than the polling frequency.

**Comment by ilayaperumalg** [comment]
Also, the bridging functionality in `BindableProxyFactory` is used **only** for the shared channels in Aggregate applications. 
The feature we introduced as part of the PR #415 uses the bridging mechanism but that is for the output channels only.

**Comment by ilayaperumalg** [comment]
Updated the PR that uses `PollingConsumer` instead of the bridge.

**Comment by mbogoevici** [comment]
@garyrussell 

> That said, does this "feature" even make sense? With an unbounded pollable input channel, the binder is likely to outpace any app and memory will fill up. That can be avoided with a bounded channel but, even then, the binder will immediately ack queued messages and they will be lost in the event of a failure.

Good question. I think that using `PollableChannels` in general has some loss potential (whether inbound and outbound), so perhaps we can document that or just decide whether we want to support that.

**Comment by mbogoevici** [comment]
Closing this as per https://github.com/spring-cloud/spring-cloud-stream/issues/436#issuecomment-205430607.

**Pull request closed without merging**
