### PR TITLE
Update spring-cloud-stream-overview.adoc

### PR DESCRIPTION
**Pull request by rjivan**
Addresses https://github.com/spring-cloud/spring-cloud-stream/issues/679

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@rjivan Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-stream&pullRequestId=680)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-stream&pullRequestId=680) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@rjivan Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-stream&pullRequestId=680)!

**Comment by ilayaperumalg** [comment]
@rjivan thanks for catching this and the PR!

**Comment by ilayaperumalg** [comment]
LGTM, rebased and merged as 4e3c43a

**Pull request closed without merging**
