### PR TITLE
Support namespace based prefixed properties

### PR DESCRIPTION
**Pull request by ilayaperumalg**
- In AggregateApplication, support specifying commandline and environment properties based on namespace for each containing applications using namespace as prefix
  - As usual, command line properties override the environment as well as the properties specified inside the application

Resolves spring-cloud/spring-cloud-stream#571

### CODE REVIEW

**Comment by ilayaperumalg** [comment]
This PR is based on top of the PR #643. The commit https://github.com/spring-cloud/spring-cloud-stream/pull/645/commits/8f939c0d3baae99e9075c26985d8c6fcfb1da5ba addresses the story for #571.

**Comment by ilayaperumalg** [comment]
Rebased.

**Comment by mbogoevici** [comment]
Here's an attempt to simplify the processing logic: https://github.com/mbogoevici/spring-cloud-stream/commit/ae5899ade4de53420d269296e91b5097bdbedc8b

**Comment by ilayaperumalg** [comment]
@mbogoevici The above approach of directly using the `RelaxedDataBinder`  would require additional efforts for the following:

1) To be able to override the properties set from various property sources based on their precedence level. With the suggested simplification, we would pass all the properties that are matching the namespace. There is neither filtering nor order of precedence handling.

2) Since we update all the **extracted** properties as `command-line` property args for the child application, we also need to modify the environment property into appropriate lower case as the upper case environment properties that are converted into `command-line` properties wouldn't work always. (for example passing --FIXED_DELAY=<?> wouldn't set @Value annotated with fixed-delay)

In this commit https://github.com/ilayaperumalg/spring-cloud-stream/commit/a1eaf2b2531a33ce501c76519a81e293c441d07e I try to fix the property overriding capability on top of your changes. But, I am still investigating the case sensitiveness issue (from environment -> commandline) with the use of `RelaxedDataBinder`.

**Comment by ilayaperumalg** [comment]
This change https://github.com/ilayaperumalg/spring-cloud-stream/commit/a244c614ea4a8f86ce728f5eb0493119fb48cd8a addresses the issue with handling environment properties as commandline properties.

**Comment by mbogoevici** [comment]
Maybe I am missing something, but for 1) isn't the ordering of the PropertySources already taking care of precedence ?

**Comment by ilayaperumalg** [comment]
The ordering is taken care only within the context of `RelaxedDataBinder`. But, we need to do 1) get the first matching arg that is derived based on the precedence inside the `RelaxedDataBinder` 2) consider the args passed via Child appConfigurer args

**Comment by mbogoevici** [comment]
@ilayaperumalg 

It's still not clear for me what '1) get the first matching arg (not all the matching args) that is derived based on the precedence inside the RelaxedDataBinder' means in this context. Deferring to the `RelaxedDataBinder` should take care of the order of precedence already (because the component takes care of it implicitly). What am I missing?

Number 2) seems like something that we can handle by manipulating the property sources before we pass them to the `RelaxedDataBinder`.

In order to move this forward, can you provide a detailed description of the order in which you think parameters should be bound as well as tests that illustrate that?

**Comment by ilayaperumalg** [comment]
> get the first matching arg (not all the matching args) that is derived based on the precedence inside the RelaxedDataBinder

This happens when the same properties are specified with different relaxed names from multiple property sources. For instance, the command line property `--<namespace>.fooValue=test` and the environment property as `<namespace>_FOO_VALUE=envtest`, then the RelaxedBinder target with the namespace gets both `fooValue=test` and `FOO_VALUE=envtest` as the result.
Hence, we need to get the first matching (which is from high precedence) property.

> seems like something that we can handle by manipulating the property sources before we pass them to the RelaxedDataBinder

Matching the args properties with the RelaxedDataBinder target can be effective as we need to match with the **relaxed** names as well.

Added some tests to depict these use cases. Also, rebased and updated the commits.

**Comment by mbogoevici** [comment]
Merged w/https://github.com/spring-cloud/spring-cloud-stream/commit/6fc6445c4fa604e7894d7da1b2a7be75992171a5

**Pull request closed without merging**
