### PR TITLE
Remove AggregateBuilder

### LINKED ISSUE #364: Fix AggregateBuilder
The `AggregateBuilder` in Spring Cloud Stream that uses **bindable** channels is broken. The bindings for the types updated in the AggregateBuilder are not bound appropriately.

### PR DESCRIPTION
**Pull request by ilayaperumalg**
- Fix the destination name
 - Set jmx domain name unique enough to set for the child contexts created

This resolves #364

### CODE REVIEW

**Comment by ilayaperumalg** [comment]
Associated sample is fixed [here] (https://github.com/spring-cloud/spring-cloud-stream-samples/pull/2)

**Comment by mbogoevici** [comment]
Based on the discussions with @ilayaperumalg and @dsyer , we could probably phase out the `AggregateBuilder` and keep the `AggregateApplicationBuilder` instead (maybe by renaming the latter for the former).

**Comment by ilayaperumalg** [comment]
Pushed the update to remove the existing `AggregateBuilder`.

**Comment by mbogoevici** [comment]
Merged w/ https://github.com/spring-cloud/spring-cloud-stream/commit/bc0723df896cae566261e025eb5ddd786430441d

**Pull request closed without merging**
