### PR TITLE
Fix `id` type on `SchemaRegistrationResponse`

### LINKED ISSUE #739: `SchemaRegistryClient`, `Schema` and `SchemaRegistrationResponse` have inconsistent types of `id`
Some use `Integer`, some use `long`.  While the value is not likely to exceed the scope of `Integer`, we need to bring some consistency into this.

### PR DESCRIPTION
**Pull request by mbogoevici**
Fixes #739

### CODE REVIEW

**Comment by ilayaperumalg** [comment]
A trivial question: while it is absolutely fine to have `Integer` or `int` for the `id` type. Doesn't make it look better if we use the primitive type across?

**Comment by ilayaperumalg** [comment]
Also, for the merging of this PR, I guess this can go into `master` as well as `1.1.x`. Given the story #739 is actually `1.1.1.RELEASE` and this PR is issued from `master`, I think that's the plan.

**Comment by mbogoevici** [comment]
Yes, we should merge this to 1.1.x as well.

When you referred to using the primitive type across I suppose you meant here: https://github.com/spring-cloud/spring-cloud-stream/blob/master/spring-cloud-stream-schema/src/main/java/org/springframework/cloud/stream/schema/client/SchemaRegistryClient.java#L48 ? I suppose we could do that.

**Comment by ilayaperumalg** [comment]
Yeah, Is there any issue updating [the SchemaRegistryClient interface](https://github.com/spring-cloud/spring-cloud-stream/blob/master/spring-cloud-stream-schema/src/main/java/org/springframework/cloud/stream/schema/client/SchemaRegistryClient.java#L48) and the [Schema](https://github.com/spring-cloud/spring-cloud-stream/blob/master/spring-cloud-stream-schema-server/src/main/java/org/springframework/cloud/stream/schema/server/model/Schema.java#L33) ?

**Comment by mbogoevici** [comment]
The PR's been updated for the `SchemaRegistryClient` interface. `Schema` id should stay nullable, as it is a `@GeneratedValue`

**Comment by ilayaperumalg** [comment]
LGTM, merging.

**Comment by ilayaperumalg** [comment]
Squashed, rebased and merged as f6073ad and also cherry-picked and pushed to 1.1.x 85db822

**Pull request closed without merging**
