### PR TITLE
1217 AvroSchemaRegistryClientMessageConverter registers schema formats inconsistently.

### PR DESCRIPTION
**Pull request by jmax01**
1217 AvroSchemaRegistryClientMessageConverter registers schema formats inconsistently.

### CODE REVIEW

**Comment by jmax01** [comment]
ugh missed checkstyle issue

**Comment by olegz** [comment]
I am not so sure about this one yet 
1. Why do we care about the visual format? If I understand correctly it doesn't affect functionality of registration, retrieval or applying the schema. If so why, this is purely a question of visual representation, correct?
2. If we were to go with "prettyPrint", why should we than do it always to make it "consistent"?

**Comment by jmax01** [comment]
What is stored in the DB?
If I am not incorrect, the representation is stored in the DB without modification.
As a user I would want them stored in a consistent fashion.

**Comment by viniciusccarvalho** [comment]
What is the inconsistency? Do you want data to be stored in pretty print? Is that the case? Inconsistency to me is if data is malformed. Don't even start on the whole human readable discusion with me...

**Comment by olegz** [comment]
@jmax01 Jus to clarify what @viniciusccarvalho said, presentation of the schema is out of scope  of schema  _application, storage and retrieval_ . Let's assume there is some UI to display schemas, then that responsibility would fall into such UI and as far as I know there are plenty of browser plugins and other tools to support that. 
So, I'll reject this one.
In any event thank you for your continuous contributions to the framework!

**Comment by jmax01** [comment]
Here is the inconsistency: 
`AvroSchemaRegistryClientMessageConverter.afterPropertiesSet`:
``` java
    //with print pretty	
    this.schemaRegistryClient.register(toSubject(schema), AVRO_FORMAT,
							schema.toString(true));
```
`AvroSchemaRegistryClientMessageConverter.resolveSchemaForWriting`:

``` java
  //The ParsedSchema.representation is not print pretty
  SchemaRegistrationResponse response = this.schemaRegistryClient.register(
  toSubject(schema), AVRO_FORMAT, parsedSchema.getRepresentation());
```
If you aren't going to allow configuration at least make it consistent, is that too much to ask?
I would recommend not storing them pretty printed to minimize overhead (generating, parsing, wire, storage, etc).

**Comment by olegz** [comment]
@jmax01 the above is indeed a valid point with regard to inconsistency and the one I missed.
But what I propose is to actually call a no arg `toString`.
Feel free to submit another PR for that if you agree.

Once again, thank you for helping out with this

**Comment by jmax01** [comment]
Sure will do.

**Comment by olegz** [comment]
@jmax01 and just to end it on the fun note I liked the `If I am not incorrect` ;) took me a while to process it ;)

**Pull request closed without merging**
