### PR TITLE
Use 'instanceof' pattern variable

### PR DESCRIPTION
**Pull request by ByungjunYou**
Use 'instanceof' pattern variable project-wide.
It is inspired by https://github.com/spring-cloud/spring-cloud-stream/pull/2606

By using 'instanceof' pattern variables, code becomes more `concise` and `robust`.

### pattern matching instanceof operator
https://docs.oracle.com/en/java/javase/17/language/pattern-matching-instanceof-operator.html
> pattern matching introduces new language enhancements that enable you to conditionally extract data from objects with code that's more concise and robust.

### CODE REVIEW

**Comment by ByungjunYou** [comment]
@sobychacko Thank you for reviewing the code. :)
I've updated authors and copyright years of the classes.

**Comment by sobychacko** [comment]
@ByungjunYou Could you rebase the PR against the latest main branch?

**Comment by ByungjunYou** [comment]
@sobychacko 
I've rebased the PR against the latest main branch ;)

**Comment by sobychacko** [comment]
@ByungjunYou PR merged upstream via https://github.com/spring-cloud/spring-cloud-stream/commit/7895025c47e10e7d3e1c6744c7b60f6ab9472c9d. Thank you for your contribution!! More are welcomed.

**Pull request closed without merging**
