### PR TITLE
GH-2843: Fix automatic Serde detection for branched function components

### PR DESCRIPTION
**Pull request by GFriedrich**
Ensures to properly store outbound type to type map for branched function component outputs.

Resolves https://github.com/spring-cloud/spring-cloud-stream/issues/2843

### CODE REVIEW

**Comment by GFriedrich** [comment]
@sobychacko: Would be great if you could also backport this to the 4.0.x line.
Thanks in advance for your help.

**Comment by sobychacko** [comment]
@GFriedrich, Any updates on when you can add the author tag?

**Comment by sobychacko** [comment]
Also, could you please rebase against the latest `main` branch?

**Comment by GFriedrich** [comment]
hey @sobychacko,
Sorry for the late response.
I'll try to tackle all the things you've mentioned by tomorrow.

**Comment by sobychacko** [comment]
Thank you, @GFriedrich, for the PR. It is now merged upstream and backported to `4.0.x`.

**Pull request closed without merging**
