### PR TITLE
Configurable subject naming for Avro classes

### PR DESCRIPTION
**Pull request by davidkalosi**
Hi All,

this PR is an attempt to provide a flexible way of controlling the subject naming for Avro classes and Schema registry integration. 

Given the model class ```org.springframework.cloud.schema.avro.User1``` the current solution is generating content type headers in the following format ```application/vnd.user1.v1+avro``` or by calling ```return schema.getName().toLowerCase();```.  Those are then registered in the schema registry with a subject user1, which is pretty ambiguous. In the current project we need a much more robust behaviour and agreed that the headers should ideally look like this ```application/vnd.org.springframework.cloud.schema.avro.User1.v1+avro``` - with the FQCN as the subject. This will then register the full class name as subject to the schema registry. 

In this PR I have extracted the naming to a separate Strategy interface and the default implementation is backward compatible and at the same time it allows to supply a custom naming strategy through the configuration. No idea if this implementation is sufficient, I am happy to take comments / suggestions to get this feature through.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@davidkalosi Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-stream&pullRequestId=1108)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-stream&pullRequestId=1108) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@davidkalosi Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-stream&pullRequestId=1108)!

**Comment by olegz** [comment]
@davidkalosi Thanks you for the contribution. We will review and follow up

**Comment by olegz** [comment]
@davidkalosi Please run the full build you'll see there check-style violations. Also, add your name with '@author' tag on all modules you've touched.
I'll continue to review meanwhile.

**Comment by davidkalosi** [comment]
@olegz any chance to have it backported into the 1.3.X release?

**Comment by sabbyanandan** [comment]
Hi, @davidkalosi. Thanks for all the great work on this! We very much appreciate it. 

We have been backporting just the bug-fixes to the older release lines. Given this improvement doesn't fit that criteria, we would like to keep it in master/2.x line. We hope to be on RC by the end of next month and aggressively aim to graduate to a GA release soon after that.

**Comment by davidkalosi** [comment]
Thanks, until then we will use our custom build on top of the 1.3 milestone with this patch applied.

**Pull request closed without merging**
