### PR TITLE
Fix compilation issue on ObservableToMessageChannelResultAdapter

### LINKED ISSUE #756: Compilation issue on reactor 3.0.4 upgrade
master has this compilation issue:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project spring-cloud-stream-reactive: Compilation failure
[ERROR] /home/travis/build/spring-cloud/spring-cloud-stream/spring-cloud-stream-reactive/src/main/java/org/springframework/cloud/stream/reactive/ObservableToMessageChannelResultAdapter.java:[50,66] method from in class reactor.core.publisher.Flux<T> cannot be applied to given types;
[ERROR] required: org.reactivestreams.Publisher<? extends T>
[ERROR] found: org.reactivestreams.Publisher<capture#1 of ?>
[ERROR] reason: cannot infer type-variable(s) T,T
[ERROR] (argument mismatch; org.reactivestreams.Publisher<capture#2 of ?> cannot be converted to org.reactivestreams.Publisher<? extends capture#2 of ?>)
[ERROR] -> [Help 1]
[ERROR] 
```

### PR DESCRIPTION
**Pull request by ilayaperumalg**
This resolves #756

### CODE REVIEW

**Comment by ilayaperumalg** [comment]
Here is the travis build failure on master: https://travis-ci.org/spring-cloud/spring-cloud-stream/builds/189346497

**Comment by jvalkeal** [comment]
Travis error happens with `jdk1.8.0_31`, but compiles fine with `jdk1.8.0_45` or `jdk1.8.0_111`. I tried all combinations so I think PR looks ok.

**Comment by jvalkeal** [comment]
as a note, afaik, this PR didn't change any functionality, just workaround for older jdk8 compilers not to error out.

**Comment by ilayaperumalg** [comment]
Cherry-picked and pushed the change to 1.1.x: c613ee5

**Pull request merged**
