### PR TITLE
Doc for non self-contained aggregate application

### LINKED ISSUE #818: Binding service properties for aggregate child application are not used when binding
When binding the aggregate child application's bindable types to external inbound/outbound binder, the binding properties are not used.

The reason for this seems to be the inclusion of `conditionalOnMissingBean` on `BindingService` [here](https://github.com/spring-cloud/spring-cloud-stream/blob/master/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/config/BindingServiceConfiguration.java#L98).

If this `conditional` check is necessary, we could as well check if using explicit `BindingServiceProperties` as a bean would be an option here.

### PR DESCRIPTION
**Pull request by ilayaperumalg**
Resolves #818

### CODE REVIEW

**Comment by jvalkeal** [comment]
Would you mind adding more info what `non self-contained` actually means. There is the sample PR for this which I didn't merge as it's missing readme for same reason. Maybe `non self-contained` is wrong wording as at least I don't connect with its meaning. It may be obvious to you but not to me.

**Comment by ilayaperumalg** [comment]
@jvalkeal sure thing.

**Comment by jvalkeal** [comment]
Thx, much better. Merging...

**Comment by jvalkeal** [comment]
Squashed/merged per https://github.com/spring-cloud/spring-cloud-stream/commit/347cac75f2bd2d8a61dba2f8332f3502ddc374f6

**Pull request closed without merging**
