### PR TITLE
Fix typos in spring-cloud-stream-overview.adoc

### PR DESCRIPTION
**Pull request by laur89**
- critiical -> critical;
- end 'etc' with a period; also consistently end etc in parentheses with
  'etc.).';
- typo in 'application';
- applicaiton -> application;

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@laur89 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-stream&pullRequestId=1100)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-stream&pullRequestId=1100) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by laur89** [comment]
As it falls in the 'obvious fix' category, I'm not going to sign the CLA.

**Comment by olegz** [comment]
@laur89 was wondering what specific issue do you have with signing the CLA? Regardless how "obvious" the contribution may be it is still a contribution. . . And CLA is really just a one-time formality that everyone in the community goes thru, and in fact inline with requirements of many other open source communities (i.e., ASF). 
Anyway, let us know how you want to proceed.

**Comment by pivotal-issuemaster** [comment]
@laur89 This Pull Request contains an obvious fix. Signing the Contributor License Agreement is not necessary.

**Comment by pivotal-issuemaster** [comment]
@laur89 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-stream&pullRequestId=1100)!

**Comment by laur89** [comment]
No specific reason. Signed it.

**Comment by olegz** [comment]
@laur89 Thank you. Merging

**Pull request merged**
