### PR TITLE
support schema-type union

### PR DESCRIPTION
**Pull request by 4shael**
#1469 For now it's not possible to use avro schemas with multiple types (or maybe I don't know how?). Using schema like this will cause an error, but schema is correct.
```javascript
[
  {
    "namespace": "com.example",
    "type": "record",
    "name": "Foo",
    "fields": [
      {
        "name": "id",
        "type": "string"
      }
    ]
  },
  {
    "namespace": "com.example",
    "type": "record",
    "name": "Bar",
    "fields": [
      {
        "name": "id",
        "type": "string"
      },
      {
        "name": "foo",
        "type": "Foo"
      }
    ]
  }
]
```
This small patch will fix this.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@4shael Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-stream&pullRequestId=1466)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-stream&pullRequestId=1466) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@4shael Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-stream&pullRequestId=1466)!

**Comment by sobychacko** [comment]
@4shael Where are you seeing the test failures?

**Comment by 4shael** [comment]
@sobychacko On CI https://travis-ci.org/spring-cloud/spring-cloud-stream/builds/424886988

**Pull request closed without merging**
