### PR TITLE
simplify KafkaMessageChannelBinder ctor call

### PR DESCRIPTION
**Pull request by mbenson**
The headers are varargs anyway, so `null` checking in the ctor makes for less overall code.

### CODE REVIEW

**Comment by mbogoevici** [comment]
Hi @mbenson,

Thanks - LGTM, will merge.

**Comment by mbogoevici** [comment]
Rebased, merged w/https://github.com/spring-cloud/spring-cloud-stream/commit/9119e794c8fcd5d11a021af231b8b51c2956c204

**Comment by mbenson** [comment]
sorry I forgot to rebase. Thanks for merging!

**Comment by mbogoevici** [comment]
No worries - it's part of the merging process! Thanks for improving code quality :)

**Pull request closed without merging**
